version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces/dotfiles:cached
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
